version: "3"

services:
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    
  backend:
    image: backend
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - ./backend/:/code/
    ports:
      - 5050:5050
