version: "3"

services:
  backend:
    image: backend
    env_file:
      - ./backend/.env
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - ./backend/:/code/
    ports:
      - 5050:5050
